language: java
sudo: false
notifications:
  slack:
    secure: g8buxb6Nh6uK8D5V5ysroPyzNIwceo1+pIDbcSVMf3tlsDScj+ECoOASJ2ANH6yXbmdJtr+soFqz/XtQbmUR5jIFj8u4tmq3QM5zUr18um9jGiaEaono+NhYKXBsp+cOytAqZar3SWQPmYUIdXAYCZJ9kmCFHtFsMec8KlYAaFqk1ddChAuyuqIa3a0uzaxVXzqkFHvsImpF4aBNlalfSmqqGcCwlvXOTfCH43ppJuIrcWybXWtzvpM4cs264fEvVg7Pt7CkKCZnO366dPEPBw6YRH4Z4afrPcuzr/IHzeCBS42WZ5flstdpZNzoWFIrPirNVgi+btQh0c+wwv3/InXidi5OzzZomc8KDEdFQEwBQqZAcnBqyzEP7wyXnpwImbAyZ0YqsKnRVwXm6eRrzeRs77txtUxwrEak2Vq7ur845phYj/G4bOeMG4cKmdW+Tqb0L/vuvhuXSmEpbIb/sDNzQsvO7A/5rzoWJFQWFSrn0HHGF7D8opmCWJjBrHlc86LdrM6w7rW0S4kJBDabEEVmRemED0sOcdBApn9hM/hffelVzX0N2ZYIJhDsy5QivRgqlsLw/l6xZxz87DZIU4++tk+ZeWtpdfg7rePoCp2C5B2q7wVykKwVKLbyDCEKAkdZjsPO0PDsGlKLi1v+eH+Ca8xy9xDZww0E5slQp4k=
deploy:
  provider: releases
  api_key:
    secure: CHK/e4BaaaX4tXPoJEytHOJ311U0idTakcxRytMMLU5/M7FBJIFnH1L66639PpYz4qiEttstpi3Z0mklW0ODrThjnb1UjyDj0uEgvAevIK9A/LCfGijqvQTeFNVrkJ9LnahtxLzPJ4EmtwdadS8YE0XS9kkl+1JMuLUGMhsSB7aSu+vBdtscrHg+d9UsOVjqToZzBN2zbqtWQt3OugAeZmXlImpnwQslHO7waKS9vWNTr+S3LuCp131lWxvEKFQl5r95qMH1IORsqcJmJ0H4sPh6LY16MmRMlWGG0P6ijmqrPMf/o8qRDhKq82Ui1UKMqDFN68PZGhf7jodA/d+q9wLfC0gDmeypgqgfnUY87hR9ReCrySuTgBkMNC2A3SbTkRf1brurocMtju2dn4v8dY08G/HQdF4XP2PDyq5xTHExRb04o7lpCW4Jc1BnwY2y1gEbHFpfO5NTf52Tw/vvlRYxK+BM+TrSzmNuHORrP+O4YZi2M+vMVXlMks14HGq8yBU9pxmQ8Pvmw+eGwSquq9/d88df1qP1BaU2yQ/RZ4hRzKAOCYSAwB1qeTb5G4VmZ6DHqgUxeMCWHD3LLElTsjxvrdkjclAmbSZtueIOaluey8tQOOL9BENtV6vh5aK5XgF2H65TxZNnp8ULU8hjKw3yNgVCXinRTKbolAAUZUY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-f5-plugin
