language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  api_key:
    secure: BYyLJQh3iLp5hWYMmEUFOCYHbzePP4plGLvGXZXUI9L3vslKXt98iKjnOJTNG+/u9U4uQQsvqyULl4qlFosCzR/VVxW5jjtVyTlao743/pPqMwF+mxi9RqkWScivd6OIx6NNY4bkvLzN/6TUzEkuF0dwxn32JzRhcxQ9I4FNgqKnFvH/B+QWmyk6nNW/uooT07iDZXXYrkxjVQLxUSjqB7ZxkQgjAUWTt42uauj4VvCc5b7yz2K9wSXTFf0mUNv/Az2zLQHzOwRI4DEoDTcjE9AE27iURsRJXLTG/no4ILr8QPGTI9M5eaKJnEWx5srDTnRXyFXYPryIvsgpMleErwyHF2ETlWNZ8IeOfEcdAFWx/jBNCyeyrx6Sq0CRvexmQgY+uh0N5O+tKSqeQx/ROOZCapBKUOQJBjeQgNqfAo/EPZxFl5j+ri8sZbPqXUxjiBWTnTAOHhLF/04u4rO8uPg0I/4VFszLSiq7jqK9fIWw38IEj8P/yoEd1yuX0Ndd+WK7j5aAZGYCu5zYpxDdz//WfcLBX8Qg+2OLTkXZtAPFY9PleuFJ/vaxCAHHHYa3OvW3WUBP8RtV6GAA+OCXeGRn8vKTXEJrzuVvZHvQX3nsFD0eMDqmrA8BCE0FdokMZm/4eukAsNkhq8ZB96tF/x7/MxgXXc33/QZnW5POuFM=
  file: build/libs/xlr-F5-plugin-1.0.0.jar
  on:
    repo: xebialabs-community/xlr-F5-plugin
