language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  api_key:
    secure: CHK/e4BaaaX4tXPoJEytHOJ311U0idTakcxRytMMLU5/M7FBJIFnH1L66639PpYz4qiEttstpi3Z0mklW0ODrThjnb1UjyDj0uEgvAevIK9A/LCfGijqvQTeFNVrkJ9LnahtxLzPJ4EmtwdadS8YE0XS9kkl+1JMuLUGMhsSB7aSu+vBdtscrHg+d9UsOVjqToZzBN2zbqtWQt3OugAeZmXlImpnwQslHO7waKS9vWNTr+S3LuCp131lWxvEKFQl5r95qMH1IORsqcJmJ0H4sPh6LY16MmRMlWGG0P6ijmqrPMf/o8qRDhKq82Ui1UKMqDFN68PZGhf7jodA/d+q9wLfC0gDmeypgqgfnUY87hR9ReCrySuTgBkMNC2A3SbTkRf1brurocMtju2dn4v8dY08G/HQdF4XP2PDyq5xTHExRb04o7lpCW4Jc1BnwY2y1gEbHFpfO5NTf52Tw/vvlRYxK+BM+TrSzmNuHORrP+O4YZi2M+vMVXlMks14HGq8yBU9pxmQ8Pvmw+eGwSquq9/d88df1qP1BaU2yQ/RZ4hRzKAOCYSAwB1qeTb5G4VmZ6DHqgUxeMCWHD3LLElTsjxvrdkjclAmbSZtueIOaluey8tQOOL9BENtV6vh5aK5XgF2H65TxZNnp8ULU8hjKw3yNgVCXinRTKbolAAUZUY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-f5-plugin
